"""add notion quote fields

Revision ID: 077ccbdb0dab
Revises: 56d5bf44187d
Create Date: 2026-08-15 15:50:57.841509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077ccbdb0dab'
down_revision: Union[str, Sequence[str], None] = '56d5bf44187d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('notion_page_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('notion_quotes_database_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notion_quotes_database_id')
    op.drop_column('quotes', 'notion_page_id')
    # ### end Alembic commands ###
